HW Selenium part2
Leontievna/EvgeniiaAgafonova_LevelUp- pull request #7
Opened 2021-01-17 12:16 UTC by Leontievna

2021-01-22 08:24 UTC, khda91 requested changes
А почему решила не использовать `PageFactory` для создания Page objects?

2021-01-22 08:24 UTC, khda91 commented on homework_5/src/main/java/pageobject/MailLetterPage.java
> +    private WebDriver driver;
А за чем в каждом page object создавать поле  `WebDriver`? 
Может быть имеет смысл вынести его в базовый класс?

2021-01-22 08:24 UTC, khda91 commented on homework_5/src/main/java/pageobject/MailLetterPage.java
> +        new WebDriverWait(driver, 10)
Можно не писать каждый раз `new WebDriverWait()`. 
Лучше сделать поле в базовом классе `private WebDriverWait wait` и потом проинициализировать его в конструкторе `wait = new WebDriverWait(driver, 10)` и использовать в коде дальше как `wait.until(...)`

2021-01-22 20:20 UTC, Leontievna commented on homework_5/src/main/java/pageobject/MailLetterPage.java
> +    private WebDriver driver;
 Вынесла. С ним и правда - лучше

2021-01-22 20:20 UTC, Leontievna commented on homework_5/src/main/java/pageobject/MailLetterPage.java
> +        new WebDriverWait(driver, 10)
Сделала

2021-01-29 16:01 UTC, khda91 approved these changes
Работа принята

2021-01-29 18:13 UTC, merged